### ISSUE TITLE
Supebuild dependances version are old

### ISSUE THREAD

**Issue by savmickael** [Sen2Agri/OTB#1]
Current TIFF version (4.0.3) is not more available:

- [tiff 4.0.3 link](http://download.osgeo.org/libtiff/tiff-4.0.3.tar.gz) return not found. I have updated in the attached patch to 4.0.4 but it seems reasonable to move to 4.0.9 (current OTB used 4.0.8).
- Current GDAL version (1.11.5) is not supported on Ubuntu 16.04 due to a bug of compilation with new gcc version. I have updated in the patch to 1.11.5.

Diff in the following file: [diff.zip](https://github.com/Sen2Agri/OTB/files/1490581/diff.zip)

**Comment by lnicola** [comment]
Thanks! I went with `libtiff 4.0.9`. We're not using SuperBuild `libtiff`, so please ping me if anything goes wrong with that.

**Comment by savmickael** [comment]
ok nice.
Thanks
